pipeline {
    agent any

    environment {
        // Reference your AWS credentials saved in Jenkins
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        ANSIBLE_SSH_KEY       = credentials('ssh-private-key') 
    }

    stages {
        // Stage 1: Git Clone happens automatically if using a Pipeline script from SCM
        stage('Stage 1 - Git Clone') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Stage 2 - Terraform Init') {
            steps {
                dir('terraform') {
                    echo 'Initializing Terraform...'
                    sh 'terraform init'
                }
            }
        }

        stage('Stage 3 - Terraform Apply') {
            steps {
                dir('terraform') {
                    echo 'Creating Infrastructure...'
                    // -auto-approve bypasses the manual [yes] prompt in CI/CD
                    sh 'terraform apply -auto-approve'
                    
                    // Optional: Extract the new App Server IP to pass to Ansible
                    sh 'terraform output app_server_ip > ../ansible/app_ip.txt'
                }
            }
        }

        stage('Stage 4 - Ansible Deployment') {
            steps {
                dir('ansible') {
                    echo 'Configuring App Server with Ansible...'
                    // Dynamically use the IP generated by Terraform if needed
                    // Ensure your ansible.cfg ignores host key checking for automation
                    sh 'ansible-playbook -i inventory install-docker.yml --private-key=${ANSIBLE_SSH_KEY}'
                }
            }
        }

        stage('Stage 5 - Docker Build') {
            steps {
                dir('docker') {
                    echo 'Building Nginx Docker Image...'
                    // Building the image locally or on the remote app server
                    sh 'docker build -t my-nginx-website:latest .'
                }
            }
        }

        stage('Stage 6 - Docker Run') {
            steps {
                echo 'Deploying Docker Container to App Server...'
                // If deploying remotely via Ansible or SSH:
                // sh "ssh -i ${ANSIBLE_SSH_KEY} user@app_ip 'docker run -d -p 80:80 my-nginx-website:latest'"
                
                echo 'Deployment successful! Nginx Website is live.'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
    }
}